matrix:
  include:
     - language: go
       os: linux
       script: GOOS=windows GOARCH=386 go build -o dnsleaktest.exe dnsleaktest.go
       before_deploy:
       deploy:
         provider: releases
         api_key: "${GITHUB_OAUTH_TOKEN}"
         file: dnsleaktest.exe
         skip_cleanup: true
         on:
           repo: macvk/dnsleaktest
           tags: true           

     - language: go
       os: linux
       script: go build -o dnsleaktest dnsleaktest.go
       before_deploy:
       deploy:
         provider: releases
         api_key: "${GITHUB_OAUTH_TOKEN}"
         file: dnsleaktest
         skip_cleanup: true
         overwrite: true
         on:
           repo: macvk/dnsleaktest
           tags: true

